-- OkoSauronaWeb.PAGEDATA definition

CREATE TABLE `PAGEDATA` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `PAGETITLE` varchar(500) DEFAULT NULL,
  `PAGELINK` varchar(500) DEFAULT NULL,
  `PAGETEXT` mediumtext,
  `PAGEDATE` datetime DEFAULT NULL,
  `PAGERELATE` enum('P','Z') DEFAULT NULL,
  `PAGEREGION` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8190 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;